### ISSUE TITLE
Package doesn't contain "www" templates folder, raises `jinja2.exceptions.TemplateNotFound: index_template.html` error.

### ISSUE THREAD

**Issue by hasansezertasan** [arnavdas88/fastwave#1]
I installed the package from the command in the README. I ran the example from the README.

It raised this error:

`jinja2.exceptions.TemplateNotFound: index_template.html`

I tried to fix the error like this:

```python
import inspect
import pathlib
import typing

# FaseAPI
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.requests import Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.types import DecoratedCallable
from h2o_lightwave import Q, data
from h2o_lightwave.server import _App
from h2o_wave.server import HandleAsync, Query

# Jinja Template Engine
from jinja2 import Environment, FileSystemLoader, PackageLoader
from starlette.background import BackgroundTask

from fastwave.utils import (
    change_signature,
    get_parameters,
    get_web_files,
    takes_websocket_as_input_parameter,
    type_support_pydantic,
)

fastwave_web_dir = str(pathlib.Path(__file__).parent / "www")

# Prepare our custom index.html and inject required JS files.
# Jinja is used for convenience, you can use any templating engine.
template = Environment(loader=PackageLoader("fastwave", "www")).get_template(
    "index_template.html"
)
```

Which is the correct way to deliver Jinja2 loaders and I noticed one more thing

There is no "www" folder in the `site-packages/fastwave` folder.

The module is not packaged correctly, it should contain the "www" folder.

**Comment by arnavdas88** [comment]
Yes, you are right!!! the setup.py lacks the necessary `package_data={...}` attribute (although i did add `
    include_package_data=True`). I will push an update for this!!!

**Comment by hasansezertasan** [comment]
If the project has nothing to do with Jinja2 templates but only delivers a single HTML file, I recommend removing it from the dependencies and returning the HTML string using f-strings. Keep in mind, I don't know the scope of h2o-wave, either this project.

**Comment by arnavdas88** [comment]
Hi @hasansezertasan , I have pushed an update https://github.com/arnavdas88/fastwave/commit/4b1eae632dca55f03d6af2f19c92246b05e06b8e and the pip install should contain the `www` directory now. Although it now contains a single Jinja templates, it "may" contain more files in the future, Hence, I decided to keep the `www` directory now instead of packaging it as a seperate static file.

I "may" change this to your suggestion, later down the road!!! 😄
